### PR TITLE
Tag habilities

### PR DESCRIPTION
**Pull request by fernandoferreira-me**
Hi,
I've work in the code for the past few days. It is now possible to have links in the word cloud. Now your awesome cloud (really awesome) is also a tag cloud. Give a look on the code.

### CODE REVIEW

**Comment by Gremlyn** [comment]
Having the word clouds clickable would be awesome! @fguimara, unfortunately it looks like your editor reset all the indentation on the code, making it very difficult to see what specifically was added, removed, or changed. Can you refork and make the changes with your indents the same as the original code?

**Comment by fernandoferreira-me** [comment]
Ohhh... Ok I will try to this till the end of this month... No problem!

**Comment by slaFFik** [comment]
Is there any update about this code? Really needed feature.

**Comment by sandipransing** [comment]
@fguimara any update?

**Pull request merged**
